
[functions.mark-booking-paid-manual]
enabled = true
verify_jwt = true
import_map = "./functions/mark-booking-paid-manual/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mark-booking-paid-manual/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mark-booking-paid-manual/*.html" ]

[functions.charge-sepa-booking]
enabled = true
verify_jwt = true
import_map = "./functions/charge-sepa-booking/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/charge-sepa-booking/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/charge-sepa-booking/*.html" ]
